base_url = https://rahulshettyacademy.com/maps/api/place
get_place_url = https://rahulshettyacademy.com/maps/api/place/get/json?{place_id}&key=qaclick123
add_place_url = https://rahulshettyacademy.com/maps/api/place/add/json
update_place_url = https://rahulshettyacademy.com/maps/api/place/update/json?place_id=bc6bda065b98b67f1ce62489a0b93c1d&key=qaclick123
delete_place_url = https://rahulshettyacademy.com/maps/api/place/delete/json?key=qaclick123